apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    purpose: statefulset-redis
    project: roboshop
    environment: dev
spec:
  selector:
    purpose: statefulset-redis
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379