apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  serviceName: redis-headless-service  # Must match headless service
  replicas: {{ .Values.statefulset.replicas }}
  minReadySeconds: 10
  selector:
    matchLabels:
      purpose: statefulset-redis
      project: roboshop
      environment: dev
  template:
    metadata:
      labels:
        purpose: statefulset-redis
        project: roboshop
        environment: dev
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis
          image: {{ .Values.statefulset.imageURL }}:{{ .Values.statefulset.imageVersion }}
          volumeMounts:
            - name: redis-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: roboshop-ebs-sc
        resources:
          requests:
            storage: 1Gi