pipeline {
    agent { label 'AGENT-1' }

    environment { 
        REGION     = "us-east-1"
    }

    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }

    stages {
        stage('Init') {
            steps {
                script {
                    withAWS(credentials: 'aws-config', region: "${REGION}") {
                        sh """
                            cd aws-eks-terraform/06-eks-blue-green
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }

        stage('Plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-config', region: "${REGION}") {
                        sh """
                            cd aws-eks-terraform/06-eks-blue-green
                            terraform plan
                        """
                    }
                }
            }
        }

        stage('Apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-config', region: "${REGION}") {
                        sh """
                            cd aws-eks-terraform/06-eks-blue-green
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }

        // stage('Trigger ACM') {
        //     steps {
        //         script {
        //             build job: '04-acm',
        //                   propagate: false, // even if ACM fails, ingress won't be blocked
        //                   wait: false       // do not wait for ACM pipeline completion
        //         }
        //     }
        // }
    }

    post {
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }

        success { 
            echo 'Hello success'
        }

        failure { 
            echo 'Hello Failed'
        }
    }
}
