apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    purpose: statefulset-mongodb
    project: roboshop
    environment: dev
spec:
  selector:
    purpose: statefulset-mongodb
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017