apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  serviceName: mongodb-headless-service  # Must match headless service
  replicas: {{ .Values.statefulset.replicas }}
  minReadySeconds: 10
  selector:
    matchLabels:
      purpose: statefulset-mongodb
      project: roboshop
      environment: dev
  template:
    metadata:
      labels:
        purpose: statefulset-mongodb
        project: roboshop
        environment: dev
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: {{ .Values.statefulset.imageURL }}:{{ .Values.statefulset.imageVersion }}
          ports:
          - containerPort: 27017
            name: mongodb
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "roboshop-ebs-sc"
        resources:
          requests:
            storage: 1Gi