apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    tier: app
    component: payment
    environment: dev
    project: roboshop
spec:
  selector:
    tier: app
    component: payment
    environment: dev
    project: roboshop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080