// Roboshop-cart service Jenkins pipeline

pipeline {
    agent { label 'AGENT-1' }

    environment { 
        AWS_ACCOUNT_ID = "069233348386"
        AWS_REGION     = "us-east-1"
        REPO_NAME      = "roboshop/cart"
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds() 
    }

    stages {
        stage('Read package.json') {
            steps {
                script {
                    sh 'ls -al'
                    def packageJson = readJSON file: 'cart/package.json'
                    appVersion = packageJson.version
                    echo "package version: ${appVersion}"
                }
            }
        }
        
        stage('Install Dependencies') {
            steps {
                sh '''
                    cd cart
                    npm install --production
                '''
            }
        }

        stage('Docker Build and Push') {
            steps {
                script {
                    withAWS(credentials: 'aws-config', region: "${env.AWS_REGION}") {
                        sh """
                            aws ecr get-login-password --region ${env.AWS_REGION} | \
                              docker login --username AWS --password-stdin ${env.AWS_ACCOUNT_ID}.dkr.ecr.${env.AWS_REGION}.amazonaws.com

                            docker build -t ${env.REPO_NAME}:${appVersion} ./cart

                            docker tag ${env.REPO_NAME}:${appVersion} \
                              ${env.AWS_ACCOUNT_ID}.dkr.ecr.${env.AWS_REGION}.amazonaws.com/${env.REPO_NAME}:${appVersion}

                            docker push ${env.AWS_ACCOUNT_ID}.dkr.ecr.${env.AWS_REGION}.amazonaws.com/${env.REPO_NAME}:${appVersion}
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Always say Hi"
            deleteDir()
        }
        success {
            echo "Pipeline is Success"
        }
        failure {
            echo "Pipeline has Failed"
        }
    }
}
