apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-shipping
  namespace: roboshop
  labels:
    tire: app
    component: shipping
    environment: dev
    project: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"