apiVersion: v1 
kind: Secret
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    purpose: statefulset-rabbitmq
    project: roboshop
    environment: dev    
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="       # base64("roboshop")
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="   # base64("roboshop123")