// Roboshop-mongodb service Jenkins pipeline

pipeline {
    agent { label 'AGENT-1' }

    environment { 
        AWS_ACCOUNT_ID = "069233348386"
        AWS_REGION     = "us-east-1"
        REPO_NAME      = "roboshop/mongodb"
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds() 
    }

    parameters {
        string(name: 'appVersion', defaultValue: '1.0.0', description: 'Image version for MongoDB')
    }

    stages {
        stage('Docker Build and Push') {
            steps {
                script {
                    withAWS(credentials: 'aws-config', region: "${env.AWS_REGION}") {
                        sh """
                            aws ecr get-login-password --region ${env.AWS_REGION} | \
                              docker login --username AWS --password-stdin ${env.AWS_ACCOUNT_ID}.dkr.ecr.${env.AWS_REGION}.amazonaws.com

                            docker build -t ${env.REPO_NAME}:${params.appVersion} ./mongodb

                            docker tag ${env.REPO_NAME}:${params.appVersion} \
                              ${env.AWS_ACCOUNT_ID}.dkr.ecr.${env.AWS_REGION}.amazonaws.com/${env.REPO_NAME}:${params.appVersion}

                            docker push ${env.AWS_ACCOUNT_ID}.dkr.ecr.${env.AWS_REGION}.amazonaws.com/${env.REPO_NAME}:${params.appVersion}
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Always say Hi"
            deleteDir()
        }
        success {
            echo "Pipeline is Success"
        }
        failure {
            echo "Pipeline has Failed"
        }
    }
}
