apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
  namespace: roboshop
  labels:
    purpose: statefulset-mysql
    project: roboshop
    environment: dev
spec:
  clusterIP: None  # Headless
  selector:
    purpose: statefulset-mysql
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306