apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
spec:
  serviceName: mysql-headless-service   # ✅ Must match headless service name
  replicas: {{ .Values.statefulset.replicas }}
  minReadySeconds: 10
  selector:
    matchLabels:
      purpose: statefulset-mysql
      project: roboshop
      environment: dev
  template:
    metadata:
      labels:
        purpose: statefulset-mysql
        project: roboshop
        environment: dev
    spec:
      serviceAccountName: roboshop-mysql-secret-reader
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 0  # ensures mounted volumes are writable by non-root users
      volumes:
        - name: mysql-secret
          emptyDir: {}   # temporary volume shared between initContainer and main container
      initContainers:
        - name: fetch-secret
          image: amazon/aws-cli:2.15.5
          securityContext:
            runAsUser: 0  # ensure write access to /mnt
          command:
            - sh
            - -c
            - |
              echo "Fetching MySQL root password from AWS SecretsManager..."
              SECRET_JSON=$(aws secretsmanager get-secret-value \
                --secret-id roboshop/mysql/password-i5ohIz \
                --query SecretString --output text)
              MYSQL_ROOT_PASSWORD=$(echo $SECRET_JSON | python3 -c "import sys, json; print(json.load(sys.stdin)['MYSQL_ROOT_PASSWORD'])")
              echo $MYSQL_ROOT_PASSWORD > /mnt/mysql_root_password.txt
              chmod 600 /mnt/mysql_root_password.txt
              echo "✅ MySQL root password saved to /mnt/mysql_root_password.txt"
          volumeMounts:
            - name: mysql-secret
              mountPath: /mnt
      containers:
        - name: mysql
          image: "{{ .Values.statefulset.imageURL }}:{{ .Values.statefulset.imageVersion }}"
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - |
              if [ -f /mnt/mysql_root_password.txt ]; then
                export MYSQL_ROOT_PASSWORD=$(cat /mnt/mysql_root_password.txt)
                echo "✅ Loaded MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD"
              else
                echo "❌ Password file not found!"
                exit 1
              fi
              exec mysqld  # use this since roboshop image has no docker-entrypoint.sh
          volumeMounts:
            - name: mysql-secret
              mountPath: /mnt
            - name: mysql-storage
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: roboshop-ebs-sc
        resources:
          requests:
            storage: 1Gi
