apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
spec:
  serviceName: mysql-headless-service
  replicas: {{ .Values.statefulset.replicas }}
  minReadySeconds: 10
  selector:
    matchLabels:
      purpose: statefulset-mysql
      project: roboshop
      environment: dev
  template:
    metadata:
      labels:
        purpose: statefulset-mysql
        project: roboshop
        environment: dev
    spec:
      serviceAccountName: roboshop-mysql-secret-reader
      terminationGracePeriodSeconds: 10
      volumes:
        - name: mysql-secret
          emptyDir: {}
      initContainers:
        - name: fetch-secret
          image: amazon/aws-cli
          command:
            - sh
            - -c
            - |
              aws secretsmanager get-secret-value \
                --secret-id roboshop/mysql/password \
                --query SecretString \
                --output text | jq -r .MYSQL_ROOT_PASSWORD > /tmp/mysql_root_password.txt
          volumeMounts:
            - name: mysql-secret
              mountPath: /tmp
      containers:
        - name: mysql
          image: "{{ .Values.statefulset.imageURL }}:{{ .Values.statefulset.imageVersion }}"
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                # Read password from the file written by initContainer
                configMapKeyRef:
                  name: dummy # placeholder, will override in entrypoint below
                  key: dummy
          command:
            - sh
            - -c
            - |
              export MYSQL_ROOT_PASSWORD=$(cat /tmp/mysql_root_password.txt) && \
              exec docker-entrypoint.sh mysqld
          volumeMounts:
            - name: mysql-secret
              mountPath: /tmp
            - name: mysql-storage
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: roboshop-ebs-sc
        resources:
          requests:
            storage: 1Gi
