# roboshop-mysql-secret-reader-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::069233348386:role/RoboshopMySQLSecretReaderRole
  name: roboshop-mysql-secret-reader
  namespace: roboshop
---
# 📌 Role: Grants read-only access to ALL resources in the "roboshop" namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: serviceaccount-role       # Name of the Role
  namespace: roboshop             # Namespace where Role is applied
rules:
- apiGroups: ["*"]                # "*" = all API groups (core, apps, batch, etc.)
  resources: ["*"]                # "*" = all resource types (pods, services, secrets, etc.)
  verbs: ["get", "watch", "list"] # Only read actions allowed (no create/update/delete)

---
# 📌 RoleBinding: Connects the Role with a ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: serviceaccount-rolebinding   # Name of the RoleBinding
  namespace: roboshop                # Same namespace as Role & ServiceAccount
subjects:
- kind: ServiceAccount               # Binding to a ServiceAccount
  name: roboshop-mysql-secret-reader # The ServiceAccount that will get the Role’s permissions
  # namespace field is optional here since RoleBinding is already namespaced
roleRef:
  kind: Role                         # Reference type (Role in this case, not ClusterRole)
  name: serviceaccount-role          # Must match the Role name defined above

