# roboshop-mysql-secret-reader-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::069233348386:role/RoboshopMySQLSecretReaderRole
  name: roboshop-mysql-secret-reader
  namespace: roboshop
