// Roboshop-catalogue service Jenkins pipeline

pipeline {
    // Pre-build stage
    agent { label 'AGENT-1' }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds() 
    }

    // Build stages
    stages {
        stage('Build Stage') {
            steps {
                script {
                    sh '''
                        echo "Building Stage"
                    '''
                }
            }
        }
        stage('Testing Stage') {
            steps {
                script {
                    sh '''
                        echo "Testing Stage"
                    '''
                }
            }
        }
        stage('Deploy Stage') {
            steps {
                script {
                    sh '''
                        echo "Deploying...."
                    '''
                }
            }
        }
    }

    post {
        always {
            echo "Always say Hi"
        }
        success {
            echo "Pipeline is Success"
        }
        failure {
            echo "Pipeline has Failed"
        }
    }
}

