pipeline {
    // Pre build stage
    angent { label 'AGENT-1'}
// build stage
stages {
    stage('Read Package Version') {
            steps {
                script {
                    def packageJson = readJSON file: 'catalogue/package.json'
                    def version = packageJson.version
                    echo "Package version: ${version}"
                }
            }
        }
}
}