pipeline {
    // Pre build stage
    agent { label 'AGENT-1'}
 environment { 
        version = ''
    }
// build stage
stages {
    stage('Read Package Version') {
            steps {
                script {
                    def packageJson = readJSON file: 'catalogue/package.json'
                    def env.version = packageJson.version
                    echo "Package version: ${env.version}"
                }
            }
        }
}
}